# Generated by Django 4.1.7 on 2023-03-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="0", max_length=200, unique=True)),
                ("founding_year", models.IntegerField(default="0", null=True)),
                (
                    "owner_name",
                    models.CharField(default="0", max_length=200, null=True),
                ),
                ("rarity", models.CharField(default="0", max_length=200, null=True)),
                (
                    "hq_address",
                    models.CharField(default="0", max_length=200, null=True),
                ),
                ("no_of_employees", models.IntegerField(default="0", null=True)),
                ("car", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("year_of_birth", models.IntegerField(default="0")),
                ("address", models.CharField(default="0", max_length=500)),
                ("gender", models.CharField(default="0", max_length=100)),
                ("phone", models.IntegerField(default="0")),
            ],
        ),
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(default="0", max_length=500)),
                ("engine", models.CharField(default="0", max_length=100)),
                ("type", models.CharField(default="0", max_length=100)),
                ("year", models.IntegerField(default="0")),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="django1.brand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default="2000-10-10")),
                ("name_of_dealer", models.CharField(default="0", max_length=200)),
                ("price", models.IntegerField(default=0, null=True)),
                (
                    "car_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_id",
                        to="django1.cars",
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_id",
                        to="django1.customers",
                    ),
                ),
            ],
        ),
    ]
