# Generated by Django 4.1.7 on 2023-03-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="car",
            field=models.CharField(default="-1", max_length=200, null=True),
        ),
    ]
