# Generated by Django 4.1.7 on 2023-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0002_alter_brand_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="no_of_employees",
        ),
        migrations.AddField(
            model_name="cars",
            name="horsepower",
            field=models.IntegerField(default="0"),
        ),
    ]
