# Generated by Django 4.1.7 on 2023-03-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0003_remove_brand_no_of_employees_cars_horsepower"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="car",
        ),
    ]
