# Generated by Django 4.1.7 on 2023-04-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0004_remove_brand_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description",
            field=models.TextField(default="0", null=True),
        ),
    ]
