# Generated by Django 4.1.7 on 2023-04-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0005_brand_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carownership",
            name="date",
        ),
    ]
