# Generated by Django 4.1.7 on 2023-04-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django1", "0006_remove_carownership_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="carownership",
            name="date",
            field=models.DateField(default="2000-10-10"),
        ),
    ]
